{"name": "test_login[case_data1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '0' == '1001'\n  - 1001\n  + 0", "trace": "self = <testcase.test_login.TestLogin object at 0x0000019D99BB4FD0>\ncase_data = {'case_data': {'pwd': 'sunday666', 'userName': 'sunDay'}, 'case_id': 2, 'case_title': '登陆失败-用户名错误', 'expected': {'code': '1001', 'msg': '用户名或密码错误！'}}\n\n    @pytest.mark.parametrize(\"case_data\", Login.case_data)\n    def test_login(self, case_data):\n        res = login_api_res(case_data[\"case_data\"])\n        expected = case_data[\"expected\"]\n        try:\n            assert jsonpath.jsonpath(res, \"$..code\")[0] == expected[\"code\"]\n            assert jsonpath.jsonpath(res, \"$..msg\")[0] == expected[\"msg\"]\n        except AssertionError as e:\n            log.error(\"用例--{}--执行未通过\".format(case_data[\"case_title\"]))\n            log.exception(e)\n>           raise e\n\ntestcase\\test_login.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <testcase.test_login.TestLogin object at 0x0000019D99BB4FD0>\ncase_data = {'case_data': {'pwd': 'sunday666', 'userName': 'sunDay'}, 'case_id': 2, 'case_title': '登陆失败-用户名错误', 'expected': {'code': '1001', 'msg': '用户名或密码错误！'}}\n\n    @pytest.mark.parametrize(\"case_data\", Login.case_data)\n    def test_login(self, case_data):\n        res = login_api_res(case_data[\"case_data\"])\n        expected = case_data[\"expected\"]\n        try:\n>           assert jsonpath.jsonpath(res, \"$..code\")[0] == expected[\"code\"]\nE           AssertionError: assert '0' == '1001'\nE             - 1001\nE             + 0\n\ntestcase\\test_login.py:21: AssertionError"}, "attachments": [{"name": "log", "source": "2ae8c514-7b6f-4cfb-a994-ffac765ff5de-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case_data", "value": "{'case_id': 2, 'case_title': '登陆失败-用户名错误', 'case_data': {'userName': 'sunDay', 'pwd': 'sunday666'}, 'expected': {'code': '1001', 'msg': '用户名或密码错误！'}}"}], "start": 1645359565146, "stop": 1645359565268, "uuid": "63a6793f-caa4-41b4-96d5-3fe1d51688bb", "historyId": "a7daf46baba11b4abc71423e14315556", "testCaseId": "c54ba4c514553f220eeed2f7e798b554", "fullName": "testcase.test_login.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-7R8S57O"}, {"name": "thread", "value": "19860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}